---
title: "Data Wrangling & Visualisation"
author: 'Arif P. Sulistiono / @arifpras'
date: "31/10/2021"
output:
  html_document:
    fig_caption: yes
    css: style.css
    number_sections: FALSE
    includes:
      after_body: footer.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Prerequisite

```{r clearing-first, echo=TRUE}
#clearing the environment
rm(list=ls())
ls()
```

```{r packages, include = FALSE}
#installing packages - all
#install.packages("tidyverse")
library(tidyverse)

#installing packages - separately
#install.packages("dplyr")
#install.packages("ggplot2")
#install.packages("tidyr")
#install.packages("readxl")

#including when we call for library(tidyverse)
library(dplyr)
library(ggplot2)
library(tidyr)

#needs to be called individually
library(readxl)

#--install.packages("easypackages")
easypackages::libraries("dplyr", "ggplot2", "tidyr", "readxl")

#--install.packages("pacman")
pacman::p_load(dplyr, ggplot2, tidyr, readxl)

#pacman::p_load(tidylog, warn.conflicts = FALSE)
#library(tidylog, warn.conflicts = FALSE)
#library(dplyr, warn.conflicts = FALSE)

library(plotly)
```

```{r include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

```{r directory, echo=TRUE}
#setting working directory
getwd()
setwd("/Users/arifpras/OneDrive - The University of Nottingham/BB_KelasData/KelasData")
#dir()
```

```{r onepiece}
#sources:
##--https://www.kaggle.com/michau96
##--https://www.kaggle.com/aditya2803
##--https://www.opfanpage.com/2018/06/29/one-piece-power-ranking-chart/
##--https://listfist.com/list-of-one-piece-characters-by-age

#".csv" files - local

#op_chapters <- read.csv(file.choose())
#op_chapters <- read.csv("/Users/arifpras/OneDrive - The University of Nottingham/BB_KelasData/KelasData/00_Datasets/OP_chapters.csv")

#op_characters <- read.csv(file.choose())
#op_characters <- read.csv("/Users/arifpras/OneDrive - The University of Nottingham/BB_KelasData/KelasData/00_Datasets/OP_characters.csv")

#op_ratings <- read.csv(file.choose())
#op_ratings <- read.csv("/Users/arifpras/OneDrive - The University of Nottingham/BB_KelasData/KelasData/00_Datasets/OP_ratings.csv")

#op_powers <- read.csv(file.choose())
#op_powers <- read.csv("/Users/arifpras/OneDrive - The University of Nottingham/BB_KelasData/KelasData/00_Datasets/OP_powers.csv")

#op_ages <- read.csv(file.choose())
#op_ages <- read.csv("/Users/arifpras/OneDrive - The University of Nottingham/BB_KelasData/KelasData/00_Datasets/OP_ages.csv")

#".xlsx" files - local
#op_chapters <- read_excel(path = "/Users/arifpras/OneDrive - The University of Nottingham/BB_KelasData/KelasData/00_Datasets/OP_all.xlsx", sheet = "OP_chapters")
#op_characters <- read_excel(path = "/Users/arifpras/OneDrive - The University of Nottingham/BB_KelasData/KelasData/00_Datasets/OP_all.xlsx", sheet = "OP_characters")
#op_ratings <- read_excel(path = "/Users/arifpras/OneDrive - The University of Nottingham/BB_KelasData/KelasData/00_Datasets/OP_all.xlsx", sheet = "OP_ratings")
op_powers <- readxl::read_excel(path = "/Users/arifpras/OneDrive - The University of Nottingham/BB_KelasData/KelasData/00_Datasets/OP_all.xlsx", sheet = 4)
op_ages <- read_excel(path = "/Users/arifpras/OneDrive - The University of Nottingham/BB_KelasData/KelasData/00_Datasets/OP_all.xlsx", sheet = "OP_ages")

#".csv" files - cloud
#op_chapters <- read.csv("https://www.dropbox.com/s/t1vrxsa4ad0m2c4/OP_chapters.csv?dl=1")
#op_characters <- read.csv("https://www.dropbox.com/s/e74njw4iw7qfzbl/OP_characters.csv?dl=1")
#op_ratings <- read.csv("https://www.dropbox.com/s/qvdhlnkyk02giuj/OP_ratings.csv?dl=1")
#op_powers <- read.csv("https://www.dropbox.com/s/t3gbzzscz438ecp/OP_powers.csv?dl=1")
#op_ages <- read.csv("https://www.dropbox.com/s/r24vzv7eyz35irr/OP_ages.csv?dl=1")

#require(devtools)
#install_github("Displayr/flipAPI")
#library(flipAPI)

#".xlsx" files - cloud
#op_chapters <- flipAPI::DownloadXLSX("https://www.dropbox.com/s/5mev3xo0cd3tc61/OP_all.xlsx?dl=0", sheet = 1)
#op_characters <- flipAPI::DownloadXLSX("https://www.dropbox.com/s/5mev3xo0cd3tc61/OP_all.xlsx?dl=0", sheet = "OP_characters")
#op_ratings <- flipAPI::DownloadXLSX("https://www.dropbox.com/s/5mev3xo0cd3tc61/OP_all.xlsx?dl=0", sheet = 3)
#op_powers <- flipAPI::DownloadXLSX("https://www.dropbox.com/s/5mev3xo0cd3tc61/OP_all.xlsx?dl=0", sheet = "OP_powers", want.data.frame = TRUE)
#op_ages <- flipAPI::DownloadXLSX("https://www.dropbox.com/s/5mev3xo0cd3tc61/OP_all.xlsx?dl=0", sheet = "OP_ages", want.data.frame = TRUE)
```

```{r checking}
str(op_powers)
str(op_ages)

glimpse(op_powers)
glimpse(op_ages)
```

***

# Data Wrangling

```{r filtering}
op_powers %>% 
  dplyr::filter(affiliations == "Marine")
```

```{r arranging}
op_powers %>%
  arrange(desc(character))
```

```{r recoding}
law <- op_powers %>% 
  mutate(character02 = 
           recode(character, 
                  "Trafalgar D. Water Law" = "Trafalgar D. Law"))
law
```

```{r slicing}
op_powers %>% 
  slice(56L)

op_powers %>% 
  slice(n())

op_powers %>% 
  slice(50:n())
```

```{r slice-min}
op_powers %>% 
  slice_min(character, n = 5, with_ties = FALSE)

op_powers %>% 
  slice_min(character, prop = 0.5, with_ties = TRUE)
```

```{r slice-tail}
op_powers %>% 
  slice_tail(n = 5)

op_powers %>% 
  slice_tail(prop = 0.5)
```

```{r slice-max}
op_powers %>% 
  slice_max(affiliations, n = 5, with_ties = FALSE)

op_powers %>% 
  slice_max(affiliations, prop = 0.5, with_ties = TRUE)
```

```{r slice-head}
op_powers %>% 
  slice_head(n = 5)

op_powers %>% 
  slice_head(prop = 0.5)
```

```{r selecting}
db03 <- op_powers %>%
  select(character, affiliations)
db03

db04 <- op_powers %>% 
  select(-level)
db04
```

```{r relocating}
db05 <- op_powers %>% 
  relocate(character, power, affiliations)
db05
```

```{r renaming}
status <- op_powers %>% 
  rename("status" = "level")
status
```

```{r counting}
op_powers %>% 
  filter(affiliations == "Marine") %>% 
  count()
```

```{r mutating}
db06 <- op_powers %>% 
  mutate(anime = "One Piece",
         power_2 = power/2)
db06
```

```{r transmuting}
db07 <- op_powers %>% 
  transmute(anime = "One Piece",
            power_2 = power/2)
db07
```

```{r group-by}
db08 <- op_powers %>% 
  arrange(affiliations, desc(power)) %>% 
  group_by(affiliations) %>% 
  mutate(rank = row_number()) %>% 
  ungroup() %>% #close the group_by()
  arrange(affiliations) %>% 
  select(character, affiliations, rank)
db08
```

```{r summarising}
db09 <- op_powers %>% 
  arrange(affiliations, desc(power)) %>% 
  group_by(affiliations) %>% 
  summarise(avg = mean(power, na.rm = TRUE),
            n = n()) %>%
  ungroup()
db09
```

```{r row-wise, eval=FALSE, include=FALSE}
db10a <- op_powers %>%
  mutate(fase1 = power*0.25,
         fase2 = power*0.75)
db01a

db10b <- db10a %>% 
  rowwise(character) %>%
  summarise(total = sum(fase1, fase2))
db01b
```

```{r df-villain}
villain_aff <- data.frame(
  character = c("Marshall D. Teach", "Charlotte Linlin", "Kaido", "Sakazuki Akainu", "Borsalino Kizaru"),
  affiliation = c("Blackbeard Pirates", "Big Mom Pirates", "Beasts Pirates", "Marine", "Marine")
)

character_power <- data.frame(
  name = c("Marshall D. Teach", "Kaido", "Sakazuki Akainu", "Monkey D. Dragon", "Silvers Rayleigh"),
  power = c(100, 100, 95, 99, 93)
)
```


```{r left-join, ref.label = 'df-villain', eval=FALSE, include=FALSE}
#mutating joins
villain_aff %>% 
  left_join(character_power, by = c("name" = "name"))
```

```{r right-join, ref.label = 'df-villain', eval=FALSE, include=FALSE}
#mutating joins
villain_aff %>% 
  right_join(character_power, by = c("character" = "name"))
```

```{r inner-join, ref.label = 'df-villain', eval=FALSE, include=FALSE}
#mutating joins
villain_aff %>% 
  inner_join(character_power, by = c("character" = "name"))
```

```{r full-join, ref.label = 'df-villain', eval=FALSE, include=FALSE}
#mutating joins
villain_aff %>% 
  full_join(character_power, by = c("character" = "name"))
```

```{r semi-join, ref.label = 'df-villain', eval=FALSE, include=FALSE}
#filtering joins
villain_aff %>% 
  semi_join(character_power, by = c("character" = "name"))
```

```{r anti-join, ref.label = 'df-villain', eval=FALSE, include=FALSE}
#filtering joins
villain_aff %>% 
  anti_join(character_power, by = c("character" = "name"))
```

```{r ifelse}
db11 <- op_powers %>% 
  mutate(villain = ifelse(affiliations == "Blackbeard Pirates", "Villain", "NA"))
db11
```

```{r df-luffy}
luffy00 <- tribble(
  ~arc, ~power,
  "1-Punk Hazard", 75,
  "2-Dressrosa", NA,
  "3-Zou", 80,
  "4-Whole Cake Island", 82,
  "5-Levely", NA
)
luffy00

luffy00 <- luffy00 %>% 
  add_row(arc = "6- Wano Country",
          power = 85)
luffy00

is.na(luffy00)

#data frame
colSums(is.na(luffy00))

mean(luffy00$power)
mean(luffy00$power, na.rm = TRUE)

#vector
which(is.na(luffy00))
sum(is.na(luffy00)) 
```

```{r filling, ref.label = 'df-luffy', eval=FALSE, include=FALSE}
luffy01 <- luffy00 %>%
  fill(power, .direction = "up") %>% 
  mutate(method = "fill")

luffy01
```

```{r na-mean, ref.label = 'df-luffy', eval=FALSE, include=FALSE}
luffy02 <- luffy00 %>% 
  mutate(
    power = replace(power, is.na(power), mean(power, na.rm = TRUE)),
    method = "mean"
    )

#luffy02$power[is.na(luffy02$power)] <- mean(luffy02$power, na.rm = TRUE)
luffy02
```

```{r interpolating, ref.label = 'df-luffy', eval=FALSE, include=FALSE}
luffy03 <- luffy00 %>% 
  mutate(power = zoo::na.approx(power),
         method = "interpolate")
luffy03
```

```{r dropping, ref.label = 'df-luffy', eval=FALSE, include=FALSE}
luffy00 %>% drop_na()
```

```{r row-bind, ref.label = 'df-luffy', eval=FALSE, include=FALSE}
luffy04 <- rbind(luffy01, luffy02, luffy03)

luffy04 <- luffy01 %>% 
  bind_rows(luffy02, luffy03)
luffy04
```

```{r col-bind, ref.label = 'df-luffy', eval=FALSE, include=FALSE}
luffy05 <- cbind(luffy01, luffy02, luffy03)

luffy05 <- luffy01 %>% 
  bind_cols(luffy02, luffy03)
luffy05
```

```{r piv-long}
db01a <-  op_powers %>%
  left_join(op_ages, by = c("character" = "name")) %>% 
  select(-level) %>% 
  relocate(character, affiliations, power, age)
db01a

db01b <- db01a %>% 
  pivot_longer(cols = power:age, 
               names_to = "variable", 
               values_to = "value")
db01b
```

```{r piv-wider, ref.label = 'piv-long', eval=FALSE, include=FALSE}
db01c <- db01b %>% 
  pivot_wider(names_from = variable,
              values_from = value)
db01c
```

```{r importing-table, eval=FALSE, include=FALSE}
writexl::write_xlsx(x = list(db01aSheet = db01a, db01bSheet = db01b, db01cSheet = db01c), path = "OnePiece.xlsx")

write.csv(db01a, file = "csv_db01a.csv")
```

***

# Data Visualisation

```{r plot01a, out.width = "100%", fig.align = "center", fig.retina = 3}
plot01a <- op_powers %>%
  left_join(op_ages, by = c("character" = "name")) %>%
  relocate(character, age, power) %>%
  #group_by(level) %>%
  slice_max(power, n = 15, with_ties = FALSE) %>%
  #ungroup() %>%
  ggplot(aes(x = reorder(character, power),
             y = age)) +
  geom_point(aes(color = factor(affiliations), size = power)) +
  coord_cartesian(expand = TRUE, clip = "on") +
  coord_flip() +
  nord::scale_color_nord("aurora") +
  xlab("") +
  ylab("Age") +
  theme_test() +
  theme(
    axis.text.x = element_text(size = 8),
    axis.ticks.x = element_blank(),
    axis.line.x = element_blank(),
    axis.title.x = element_text(size = 7),
    axis.line.y = element_blank(),
    axis.title.y = element_text(size = 7),
    axis.text.y = element_text(size = 8),
    plot.title.position = "plot",
    plot.caption.position = "plot",
    legend.title = element_text(size = 7),
    legend.text = element_text(size = 7),
    legend.key.size = unit(0.5, "cm"),
    legend.spacing = unit(1, "cm"),
    plot.title = element_text(hjust = 0, size = 13, face = "bold"),
    plot.subtitle = element_text(hjust = 0, size = 12),
    plot.caption = element_text(hjust = 0, size = 12),
    # legend.title = element_blank(),
    legend.position = "right",
    strip.text.x = element_text(size = 8),
    panel.grid.major.y = element_line(colour = "grey97"),
    panel.ontop = FALSE,
    panel.spacing = unit(1, "lines")
  ) +
  guides(size = guide_legend("Power"), color = guide_legend("Affiliation")) +
  labs(title = "The top 15-most powerful characters",
       subtitle = "",
       caption = "") +
  scale_size_continuous(range = c(1, 5)) +
  scale_y_continuous(limits = c(10, 90),
                     breaks = c(20, 50, 80))

plot01a
```

```{r saving-image}
ggsave(
  filename = "plot01a.png",
  plot = plot01a,
  #device = cairo_pdf,
  width = 297,
  height = 210,
  units = "mm"
)
```

```{r plot01b, out.width = "100%", fig.align = "center", fig.retina = 3}
plot01b <- op_powers %>%
  left_join(op_ages, by = c("character" = "name")) %>%
  relocate(character, age, power) %>%
  #group_by(level) %>%
  slice_max(power, n = 15, with_ties = FALSE) %>%
  #ungroup() %>%
  ggplot(aes(x = reorder(character, power),
             y = age)) +
  geom_point(aes(color = factor(affiliations), size = power)) +
  coord_cartesian(expand = TRUE, clip = "on") +
  coord_flip() +
  nord::scale_color_nord("aurora") +
  xlab("") +
  ylab("Age") +
  theme_test() +
  theme(
    axis.text.x = element_text(size = 8),
    axis.ticks.x = element_blank(),
    axis.line.x = element_blank(),
    axis.title.x = element_text(size = 7),
    axis.line.y = element_blank(),
    axis.title.y = element_text(size = 7),
    axis.text.y = element_text(size = 8),
    plot.title.position = "plot",
    plot.caption.position = "plot",
    legend.title = element_text(size = 7),
    legend.text = element_text(size = 7),
    legend.key.size = unit(0.5, "cm"),
    legend.spacing = unit(1, "cm"),
    plot.title = element_text(hjust = 0, size = 13, face = "bold"),
    plot.subtitle = element_text(hjust = 0, size = 12),
    plot.caption = element_text(hjust = 0, size = 12),
    # legend.title = element_blank(),
    legend.position = "right",
    strip.text.x = element_text(size = 8),
    panel.grid.major.y = element_line(colour = "grey97"),
    panel.ontop = FALSE,
    panel.spacing = unit(1, "lines")
  ) +
  guides(size = guide_legend("Power"), color = guide_legend("Affiliation")) +
  labs(title = "The top 15-most powerful characters",
       subtitle = "",
       caption = "") +
  scale_size_continuous(range = c(1, 5)) +
  scale_y_continuous(limits = c(10, 90),
                     breaks = c(20, 50, 80)) +
  facet_grid(. ~ level)

plot01b
```

```{r plot02a, out.width = "100%", fig.align = "center", fig.retina = 3, fig.cap = 'Figure 3: The top 15-most powerful characters, without ***facet_grid(. ~ level)***', fig.topcaption = TRUE}
plot02a <- op_powers %>%
  left_join(op_ages, by = c("character" = "name")) %>%
  relocate(character, age, power) %>%
  #group_by(level) %>%
  slice_max(power, n = 15, with_ties = FALSE) %>%
  #ungroup() %>%
  mutate(text = paste(
    "Character: ", reorder(character, power), 
    "\nAffiliation: ", factor(affiliations), 
    "\nAge: ", age, 
    "\nPower: ", power, 
    sep = "")) %>%
  ggplot(aes(x = reorder(character, power),
             y = factor(affiliations),
             text = text)) +
  geom_point(aes(color = age, size = power)) +
  coord_cartesian(expand = TRUE, clip = "on") +
  coord_flip() +
  #nord::scale_color_nord("victory_bonds", discrete = FALSE) +
  viridis::scale_colour_viridis(option = "viridis", direction = -1) +
  xlab("") +
  ylab("") +
  theme_test() +
  theme(
    axis.text.x = element_text(
      size = 8,
      angle = 90,
      vjust = 0.5,
      hjust = 1
    ),
    axis.ticks.x = element_blank(),
    axis.line.x = element_blank(),
    axis.title.x = element_text(size = 7),
    axis.line.y = element_blank(),
    axis.title.y = element_text(size = 7),
    axis.text.y = element_text(size = 8),
    plot.title.position = "plot",
    plot.caption.position = "plot",
    legend.title = element_text(size = 7),
    legend.text = element_text(size = 7),
    legend.key.size = unit(0.5, "cm"),
    legend.spacing = unit(1, "cm"),
    plot.title = element_text(hjust = 0, size = 13, face = "bold"),
    plot.subtitle = element_text(hjust = 0, size = 12),
    plot.caption = element_text(hjust = 0, size = 12),
    # legend.title = element_blank(),
    legend.position = "none",
    strip.text.x = element_text(size = 8),
    panel.grid.major.y = element_line(colour = "grey97"),
    panel.ontop = FALSE
  ) +
  guides(size = guide_legend("Power"), color = guide_colorbar("Age")) +
  labs(title = "",
       subtitle = "",
       caption = "") +
  scale_size_continuous(range = c(1, 5))
  
ggplotly(plot02a, tooltip = "text")
```

```{r plot02b, out.width = "100%", fig.align = "center", fig.retina = 3, fig.cap = "Figure 4: The top 15-most powerful characters, with ***facet_grid(. ~ level)***", fig.topcaption = TRUE}
plot02b <- op_powers %>% 
  left_join(op_ages, by = c("character" = "name")) %>% 
  relocate(character, age, power) %>% 
  #group_by(level) %>% 
  slice_max(power, n = 15, with_ties = FALSE) %>%
  #ungroup() %>% 
  mutate(text = paste(
    "Character: ", reorder(character, power), 
    "\nAffiliation: ", factor(affiliations), 
    "\nAge: ", age, 
    "\nPower: ", power, 
    sep = "")) %>%
  ggplot(aes(x = reorder(character, power), 
             y = factor(affiliations),
             text = text)) +
  geom_point(aes(color = age, size = power)) +
  coord_cartesian(expand = TRUE, clip = "on") +
  coord_flip() +
  #nord::scale_color_nord("victory_bonds", discrete = FALSE) +
  viridis::scale_colour_viridis(option = "viridis", direction = -1) +
  xlab("") +
  ylab("") +
  theme_test() +
  theme(
    axis.text.x = element_text(size = 8, angle = 90, vjust = 0.5, hjust=1),
    axis.ticks.x = element_blank(),
    axis.line.x = element_blank(),
    axis.title.x = element_text(size = 7),
    axis.line.y = element_blank(),
    axis.title.y = element_text(size = 7),
    axis.text.y = element_text(size = 8),
    plot.title.position = "plot",
    plot.caption.position = "plot",
    legend.title = element_text(size = 7),
    legend.text = element_text(size = 7),
    legend.key.size = unit(0.5, "cm"),
    legend.spacing = unit(1, "cm"),
    plot.title = element_text(
      hjust = 0, size = 13, face = "bold"
    ),
    plot.subtitle = element_text(hjust = 0, size = 12),
    plot.caption = element_text(hjust = 0, size = 12),
    # legend.title = element_blank(),
    legend.position = "none",
    strip.text.x = element_text(size = 8),
    panel.grid.major.y = element_line(colour = "grey97"),
    panel.ontop = FALSE,
    panel.spacing = unit(1, "lines")
  ) +
  guides(size = guide_legend("Power"), color = guide_colorbar("Age")) +
  labs(
    title = "",
    subtitle = "",
    caption = ""
  ) +
  scale_size_continuous(range = c(1,5)) +
  facet_grid(.~level)

ggplotly(plot02b, tooltip = "text")
```

***

# Clearing

```{r clearing-last, echo=TRUE}
#clearing the environment
ls()
rm(list=ls())
```